version: "3.1"

services: 
    database:
        image: postgres:13-alpine
        environment: 
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports: 
            - "5432:5432"
    database-admin:
        image: dpage/pgadmin4
        environment: 
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: admin
        ports: 
            - "16543:80"
        depends_on: 
            - database